# Generated by Django 2.2 on 2019-11-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_category_in_country',
        ),
        migrations.AddField(
            model_name='product',
            name='id_category',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='id_country',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
